= quarkus-hibernate-reactive-panache Project
:toc:left
:icons: font
:source-highlighter: rouge
:description: Example project for using Hibernate Reactive Panache in Quarkus.

== Requirements

=== Mariadb database

This project requires a mariadb database to run. This database can be provided by a container.
The following instructions will provide a mariadb container with [Podman](https://podman.io/).

Create the database POD.

NOTE: The database port mapping must be the one informe in the link:src/main/resources/application.properties[application.properties] file.

[source,shell script]
----
podman pod create -p 7736:3306 --name quarkus_example_db_pod
----

[source,shell script]
----
podman run --rm --name quarkus_example_db -e MYSQL_ROOT_PASSWORD=quarkus_example -e MYSQL_DATABASE=quarkus_example -e MYSQL_USER=quarkus_example -e MYSQL_PASSWORD=quarkus_example --pod quarkus_example_db_pod mariadb:latest
----

== Quarkus Intro

This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

=== Running the application in dev mode

You can run your application in dev mode that enables live coding using:
[source,shell script]
----
./gradlew quarkusDev
----

NOTE: Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

=== Packaging and running the application

The application can be packaged using:
[source,shell script]
----
./gradlew build
----

It produces the `quarkus-run.jar` file in the `build/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `build/quarkus-app/lib/` directory.

If you want to build an _über-jar_, execute the following command:
[source,shell script]
----
./gradlew build -Dquarkus.package.type=uber-jar
----

The application is now runnable using `java -jar build/quarkus-app/quarkus-run.jar`.

=== Creating a native executable

You can create a native executable using:
[source,shell script]
----
./gradlew build -Dquarkus.package.type=native
----

Or, if you don't have GraalVM installed, you can run the native executable build in a container using:
[source,shell script]
----
./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
----

You can then execute your native executable with: `./build/quarkus-hibernate-reactive-panache-1.0.0-SNAPSHOT-runner`

If you want to learn more about building native executables, please consult https://quarkus.io/guides/gradle-tooling.

=== Provided Code

==== RESTEasy JAX-RS

Easily start your RESTful Web Services

[Related guide section...](https://quarkus.io/guides/getting-started#the-jax-rs-resources)
